//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                        __o = row["MaSan"] as string;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\06C78531A0E76F93F560FD195F105C20AF67\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\11\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\9\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\4\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\17\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\16\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\15\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\14\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\13\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\10\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\B23C4102874E44756E54973366794D8F2FF7\8\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\7\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\5\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
  
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
    foreach (var row in Model)
    {
        

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                __o = row["TenSan"] as string;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                           __o = row["AnhSan"] as string;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                                                                          __o = row["DiaChi"] as string;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                               __o = Convert.ToInt32(row["SoLuongSan"]);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                                       __o = Convert.ToInt32(row["SoSanConTrong"]);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
              
        

#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\25BE6B2E8F039E0B75B2E7A00046233B0839\2\QuanLySanBanh\QuanLySanBanh\Views\Sans\Index.cshtml"
                  
    }

#line default
#line hidden
}
}
}
