//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using QuanLySanBanh;

public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
#line hidden
public _Page_Views_Shared_Error_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
private void @__RazorDesignTimeHelpers__() {
#pragma warning disable 219

#line 1 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\Error.cshtml"
       System.Web.Mvc.HandleErrorInfo __inheritsHelper = null;


#line default
#line hidden
#pragma warning restore 219
}
public override void Execute() {

#line 2 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Error_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Error_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\Error.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";


#line default
#line hidden
}
}
}
