//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
  
    String maTK = HttpContext.Current.Request.Cookies["MaTK"]?.Value;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
  
    String maTK = HttpContext.Current.Request.Cookies["MaTK"]?.Value;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
  
    String maTK = HttpContext.Current.Request.Cookies["MaTK"]?.Value;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\11\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\9\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\7\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\14\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\10\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\8\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("Styles", false);


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
       __o = RenderBody();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\Shared\LayoutAdmin.cshtml"
  
    Layout = "~/Views/Shared/_Layout1.cshtml";


#line default
#line hidden
}
}
}
