//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\7\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\6AAA22EDCCC09F98D58EB2BFF1C8ABDE01FA\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\12\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\11\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\27288B59B392BF88740EDFCE29BE64CCF113\3\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = "~/Views/Shared/LayoutAdmin2.cshtml";


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\15\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = null;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Home_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Home_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\Sans\Home.cshtml"
  
    Layout = null;


#line default
#line hidden
}
}
}
