//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\2\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\E970E778DB381D80D9072D7381E603457014\4\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
      
    ViewBag.Title = "DanhSachSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaTK", rowsPerPage: 4 );
        

#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
   __o = Scripts.Render("~/Scripts/jquery-1.6.2.min.js");


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                                                        
    

#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("MatKhau","Mật Khẩu"),
            grid.Column("Email","Email"),
            grid.Column("HoTen","Họ Tên"),
            grid.Column("SDT","Số điện thoại"),
            grid.Column("Vip","Vip"),
            grid.Column("DiemTich","Điểm tích"),
            grid.Column("Quyen","Quyền"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "Sans",new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
            grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                    __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
                 })),

            }
            );


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = Html.ActionLink("Create New", "Create");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.TenTK);


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.MatKhau);


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Email);


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.HoTen);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.SDT);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.DiaChi);


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Vip);


#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.DiemTich);


#line default
#line hidden

#line 12 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Quyen);


#line default
#line hidden

#line 13 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
foreach (var item in Model) {
    

#line default
#line hidden

#line 14 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.TenTK);


#line default
#line hidden

#line 15 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.MatKhau);


#line default
#line hidden

#line 16 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Email);


#line default
#line hidden

#line 17 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.HoTen);


#line default
#line hidden

#line 18 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.SDT);


#line default
#line hidden

#line 19 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.DiaChi);


#line default
#line hidden

#line 20 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Vip);


#line default
#line hidden

#line 21 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.DiemTich);


#line default
#line hidden

#line 22 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Quyen);


#line default
#line hidden

#line 23 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Sửa thông tin", "Edit", new { id=item.MaTK });


#line default
#line hidden

#line 24 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Chi tiết", "Details", new { id=item.MaTK });


#line default
#line hidden

#line 25 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Xóa tài khoản", "Delete", new { id=item.MaTK });


#line default
#line hidden

#line 26 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\15\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
         
}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = Html.ActionLink("Create New", "Create");


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.TenTK);


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.MatKhau);


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Email);


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.HoTen);


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.SDT);


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.DiaChi);


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Vip);


#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.DiemTich);


#line default
#line hidden

#line 12 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Quyen);


#line default
#line hidden

#line 13 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
foreach (var item in Model) {
    

#line default
#line hidden

#line 14 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.TenTK);


#line default
#line hidden

#line 15 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.MatKhau);


#line default
#line hidden

#line 16 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Email);


#line default
#line hidden

#line 17 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.HoTen);


#line default
#line hidden

#line 18 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.SDT);


#line default
#line hidden

#line 19 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.DiaChi);


#line default
#line hidden

#line 20 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Vip);


#line default
#line hidden

#line 21 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.DiemTich);


#line default
#line hidden

#line 22 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Quyen);


#line default
#line hidden

#line 23 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Sửa thông tin", "Edit", new { id=item.MaTK });


#line default
#line hidden

#line 24 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Chi tiết", "Details", new { id=item.MaTK });


#line default
#line hidden

#line 25 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Xóa tài khoản", "Delete", new { id=item.MaTK });


#line default
#line hidden

#line 26 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\14\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
         
}

#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
__o = Html.ActionLink("Create New", "Create");


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.TenTK);


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.MatKhau);


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Email);


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.HoTen);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.SDT);


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.DiaChi);


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Vip);


#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.DiemTich);


#line default
#line hidden

#line 12 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayNameFor(model => model.Quyen);


#line default
#line hidden

#line 13 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
foreach (var item in Model) {
    

#line default
#line hidden

#line 14 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.TenTK);


#line default
#line hidden

#line 15 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.MatKhau);


#line default
#line hidden

#line 16 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Email);


#line default
#line hidden

#line 17 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.HoTen);


#line default
#line hidden

#line 18 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.SDT);


#line default
#line hidden

#line 19 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.DiaChi);


#line default
#line hidden

#line 20 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Vip);


#line default
#line hidden

#line 21 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.DiemTich);


#line default
#line hidden

#line 22 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.DisplayFor(modelItem => item.Quyen);


#line default
#line hidden

#line 23 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Sửa thông tin", "Edit", new { id=item.MaTK });


#line default
#line hidden

#line 24 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Chi tiết", "Details", new { id=item.MaTK });


#line default
#line hidden

#line 25 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
       __o = Html.ActionLink("Xóa tài khoản", "Delete", new { id=item.MaTK });


#line default
#line hidden

#line 26 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\10\QuanLySanBanh\QuanLySanBanh\Views\TaiKhoans\Index.cshtml"
         
}

#line default
#line hidden
}
}
}
