//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_DatSans_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_DatSans_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_DatSans_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_DatSans_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\14\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\16C9662830E4E2B3C1795402622468751BFC\11\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\12\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\752F02A9FA85C67EF48A8F4B0E9F2AB3A328\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\10\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\9\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\8\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                               __o = ViewBag.maCTS;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            .ngayDat;

gioBatDaudefault
#line hidden

#line 5 "C:\Users\p7t22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                                      .gioBatDau;
tenSandefault
#line hidden

#line 6 "C:\Users\p8t22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         .tenSan;


viTriSandefault
#line hidden

#line 7 "C:\Users\p9t22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                  __o = ViewBag.maSan;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\5\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                           __o = ViewBag.tongTien;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\0B77C3F2B088123D7408A553121C16F4BA76\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.tenSan;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\1D7F28A103767E3F53FD6C8397FADC621953\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\7\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\7\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\7\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\7\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\7\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                             __o = ViewBag.tenSan;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\7\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});


#line 3 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                         __o = ViewBag.ngayDat;


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                                            __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                             __o = ViewBag.tenSan;


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\4\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.ngayDat;


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                             __o = ViewBag.gioBatDau;


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.tenSan;


#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\0B4032C06340A902E8645254A77DCBC58B47\6\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
                                            __o = ViewBag.viTriSan;


#line default
#line hidden
-----------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\2\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\5891E5C6F18EA026541A0489757CDA19B53C\3\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\18\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\18\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
DefineSection("Scripts", () => {

});

tml.ActionLink("Đăng xuất", "Login", new {}, new { @class = "btn btn-outline-pri7ary" } );8

#lin9default
10ine hidde11

#line 12 "C:\Users\anhla\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\18\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
       __o = Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaTK }, new{@class = "btn btn-outline-danger"});


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_PhieuDatSan_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_PhieuDatSan_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\D2D4B59C055EA7F5079DE853175E0790F999\16\QuanLySanBanh\QuanLySanBanh\Views\DatSans\PhieuDatSan.cshtml"
  
    ViewBag.Title = "PhieuDatSan";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
}
}
}
