//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
using System.Data;

#line default
#line hidden

public class _Page_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var rows = (ViewBag.Rows as DataTable)?.AsEnumerable().Select(row => new { TenSan = row["TenSan"], SoLuotDatSan = row["SoLuotDatSan"], DoanhThu = row["DoanhThu"] });
    var grid = new WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    if (rows != null)
    {
        grid = new WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    }


#line default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            using (Html.BeginForm("BaoCaoThongKe", "DatSans", FormMethod.Get))
            {
            

#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
       __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
            

#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                    __o = ViewBag.thang;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                  
            

#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                               
            }

#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
   __o = grid.GetHtml(
                         tableStyle: "table table-bordered table-hover m-0",
                         footerStyle: "grid-footer",
                         fillEmptyRows: true,
                         mode: WebGridPagerModes.Numeric,
                         alternatingRowStyle: "alternatingRowStyle",
                         columns: new[]
{
    grid.Column("STT", format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("TenSan", "Tên sân"),
    grid.Column("SoLuotDatSan", "Số lượt đặt", canSort: false),
    grid.Column("DoanhThu", "Doanh thu", canSort: false,format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
              
        var doanhThu = item.DoanhThu;
        if (!DBNull.Value.Equals(doanhThu) && doanhThu is decimal)
        {
            var DoanhThu = ((decimal)doanhThu).ToString("#,##0");
                

#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            __o = DoanhThu + " vnđ";


#line default
#line hidden

#line 12 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
        }
            

#line default
#line hidden

#line 13 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
         }))
}
);


#line default
#line hidden

#line 14 "C:\Users\pnt22\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                             __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
using System.Data;

#line default
#line hidden

public class _Page_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var rows = (ViewBag.Rows as DataTable)?.AsEnumerable().Select(row => new { TenSan = row["TenSan"], SoLuotDatSan = row["SoLuotDatSan"], DoanhThu = row["DoanhThu"] });
    var grid = new WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    if (rows != null)
    {
        grid = new WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    }


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            using (Html.BeginForm("BaoCaoThongKe", "DatSans", FormMethod.Get))
            {
            

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
       __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
            

#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                    __o = ViewBag.thang;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                  
            

#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                               
            }

#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
   __o = grid.GetHtml(
                         tableStyle: "table table-bordered table-hover m-0",
                         footerStyle: "grid-footer",
                         fillEmptyRows: true,
                         mode: WebGridPagerModes.Numeric,
                         alternatingRowStyle: "alternatingRowStyle",
                         columns: new[]
{
    grid.Column("STT", format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("TenSan", "Tên sân"),
    grid.Column("SoLuotDatSan", "Số lượt đặt", canSort: false),
    grid.Column("DoanhThu", "Doanh thu", canSort: false,format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
              
        var doanhThu = item.DoanhThu;
        if (!DBNull.Value.Equals(doanhThu) && doanhThu is decimal)
        {
            var DoanhThu = ((decimal)doanhThu).ToString("#,##0");
                

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            __o = DoanhThu + " vnđ";


#line default
#line hidden

#line 12 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
        }
            

#line default
#line hidden

#line 13 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
         }))
}
);


#line default
#line hidden

#line 14 "C:\Users\anhla\AppData\Local\Temp\4EF7DA4CB71AD338724811651986C466C0D6\5\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                             __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
using System.Data;

#line default
#line hidden

public class _Page_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var rows = (ViewBag.Rows as DataTable)?.AsEnumerable().Select(row => new { TenSan = row["TenSan"], SoLuotDatSan = row["SoLuotDatSan"], DoanhThu = row["DoanhThu"] });
    var grid = new WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    if (rows != null)
    {
        grid = new WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    }


#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            using (Html.BeginForm("BaoCaoThongKe", "DatSans", FormMethod.Get))
            {
            

#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
       __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
            

#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                    __o = ViewBag.thang;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                  
            

#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                               
            }

#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
   __o = grid.GetHtml(
                         tableStyle: "table table-bordered table-hover m-0",
                         footerStyle: "grid-footer",
                         fillEmptyRows: true,
                         mode: WebGridPagerModes.Numeric,
                         alternatingRowStyle: "alternatingRowStyle",
                         columns: new[]
{
    grid.Column("STT", format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
    grid.Column("TenSan", "Tên sân"),
    grid.Column("SoLuotDatSan", "Số lượt đặt", canSort: false),
    grid.Column("DoanhThu", "Doanh thu", canSort: false,format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
              
        var doanhThu = item.DoanhThu;
        if (!DBNull.Value.Equals(doanhThu) && doanhThu is decimal)
        {
            var DoanhThu = ((decimal)doanhThu).ToString("#,##0");
                

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            __o = DoanhThu + " vnđ";


#line default
#line hidden

#line 12 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
        }
            

#line default
#line hidden

#line 13 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
         }))
}
);


#line default
#line hidden

#line 14 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\10\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                             __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
using System.Data;

#line default
#line hidden

public class _Page_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var grid = new WebGrid(null, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    var rows = ViewBag.Rows as DataTable;
    if (rows != null)
    {
        gridnewnew WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9)
    }
 


#line default
#line hidden

#li3e 4 "C:\User3\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
lt
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724444B0927E9\9\Quan5ySanBanh\QuanLySanBanh\Are            4  DatSans\BaoCaoThongKe.cshtml"
                                    
            

#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724454B0967E9\9\QuanLySanBanh\QuanLy            5                               gKe.cshtml"
                  
            

#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724464B0927E9\9\QuanLySanBa7h\QuanLySanBanh\Areas\Admi            6                     ml"
                               
            }

#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724474B0927E989\QuanLySanBanh\QuanLySanBanh\Areas\Ad7in\Views\DatSans\BaoCaoThongKe.cshtml"
   __o = grid.                                                    __o = ;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
GetHtml(
                         tableStyle: "table table-bordered tabl8-hover",
                         footerStyle: "grid-footer",
        9                fillEmptyR   
        8                        mode: WebGridPagerModes.Numeric,
                         alternatingRowStyle: "alternatingRowStyle",9                         columns: new[]  // colums in grid
                         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("TenSan","Tên sân"),
            grid.Column("SoLuongDatSan","Số lượng"),
            grid.Column("DoanhThu","Doanh thu"),
}
);


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppDat8Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                    __o = ViewBag.TB;


#line default
#line hi#line 1 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
using System.Data;

#line default
#line hidden

2  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
    var grid = new WebGrid(null, canPage: true, defaultSort: "TenSan", rowsPerPage: 9);
    var rows = ViewBag.Rows as DataTable;
    if (rows != null)
    {
        gridnew WebGrid(rows, canPage: true, defaultSort: "TenSan", rowsPerPage: 9)    }
3344556                                              9 
#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26)      item =  new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                           default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBan;
            

#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                = ormattedDoanhThu; + " vnđ"


#line default
#line hidden

#line 12 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                    lse
        {
            

#line default
#line hidden

#line 13 "C     Admin\Views\DatSans\Bao15oThongKe.cshtml"                  13                                                                                                                                   
#line 14 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\9\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                                   __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
       __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
hongKe_cshtml()

#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"   __o = grid.GetHtml(
                         tableStyle: "table table-bordered table-hover",
                         footerStyle: "grid-footer",
                         fillEmptyRows: true,
                         mode: WebGridPagerModes.Numeric,
                         alternatingRowStyle: "alternatingRowStyle",
                         columns: new[]  // colums in grid
                         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("Email","Email"),nsColine 8 "C:\Users\pnt22\AppData\Local\Temp\E7EF308A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                __o = Url.Action("Details",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                __o = Url.Action("Delete",
                        new { id = item.MaTK});


#line default
#line hidden

#line 11 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                 })),

   }
   );


#line default
#line hidden

#line 12 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"

                                                                    __o =             6                     7  __o = 8rid.GetHtml(
                        7tableStyle: "table table-bordered table-hover",
                                                         __o = ;


#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                    footerStyle: "grid-footer",
                        8fillEmptyRows: true,
                         mode: WebGridPagerModes.N9meric,
                     rnatingRo8Sty            "alternatingRowStyle",
                         columns: new[]  // colums in grid
                         {
9           grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaTK","Mã tài khoản"),
            grid.Column("TenTK","Tên tài khoản"),
            grid.Column("Email","Email"),nsColine 8 "C:\Users\anhla\AppData\Local\Temp\E7EF308A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
         8     __o = Url.Action("Edit",
                        new { id = item.MaTK} );


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Vie                                              9 
#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26)      item =  new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                           default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBan;
                

#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtm                __ = formattedDoanh + " vnđ"Thu;


#line default
#line hidden

#line 12 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml                                                      else
        {
                

#line default
#line hidden

#li     LySanBanh\Areas\Admin\Views\DatSans\Bao15oThongKe.cshtml"  13                                                                                                                                     {
#line 14 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                                   __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
       __o = string.Format("{0:#,##0} vnđ", @ViewBag.tongTien);


#line default
#line hidden
AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
anLySanBan;


#line default
#line hidden
}
}
}
CaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 8 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                    __o = 
#line 2 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD;


#line default
#line hidden

#line 9 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                    __o =             {
            

#line default
#line hidden

#line 3 ;


#line default
#line hidden

#line 10 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                    __o = BaoCaoThongKe.cshtml"
       __o = Html.AntiForgeryToken();


#l;


#line default
#line hidden

#line 11 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B64797172441             SanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                     })                 h\QuanLySanBanh\;


#line default
#line hidden

#line 12 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B64797 414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
       ;


#line default
#line hidden

#line 12 "C:\Users\pnt22\AppData\Local\Temp\E7EF3028A6C26D38B64797 414B0927E9\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
       Areas\Admin\Vie

#line default
#line hidden

#line 13 "C:\Users\anhla\AppData\Local\Temp\E7EF3028A6C26D38B647971724414B0927E9\8\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                    __o = .cshtml"
;


#line default
#line hidden
}
}
}
ault
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\7\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                               
            }

#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\7\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                    __o = ViewBag.TB;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";


#line default
#line hidden

#line 2 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            using (Html.BeginForm())
            {
            

#line default
#line hidden

#line 3 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
       __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 4 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                    
            

#line default
#line hidden

#line 5 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                  
            

#line default
#line hidden

#line 6 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                               
            }

#line default
#line hidden

#line 7 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\6\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                    __o = ViewBag.TB;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Areas_Admin_Views_DatSans_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Areas_Admin_Views_DatSans_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/_Layout2.cshtml";



#line default
#line hidden

#line 2 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
            using (Html.BeginForm("Index", "ChiTie             {
            
                    {
            
  default
#line hidden

#line 3 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtm           __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 4 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Viewsr                                                                        
            

#line default
#line hidden

#line 5 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                  
            

#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                               
            }

#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"

B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                    __o = 
/*grid;
;


#line default
#line hidden
}
}
}
tem.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 6 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                __o = MaSan },"SansController")),*/
grid.Column("Chức năng", format: ite;


#line default
#line hidden

#line 7 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                __o = Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                    __o = U;


#line default
#line hidden

#line 8 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                __o = in\Views\DatSans\BaoCaoThongKe.cshtml"
                    __o = Ur;


#line default
#line hidden

#line 9 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
     })          ;


#line default
#line hidden

#line 10 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                                                                    __o = anh\QuanLy;


#line default
#line hidden
}
}
}
Ke.cshtml"
     })),

}
);


#line default
#line hidden

#line 19 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh                                                                                                                                    __o = ViewBag.TB;


#line default
#line hidden
}
}
}
Edit", "Sans",new { id = item.MaSan },"SansController")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","Sans", new { id = item.MaSan },"SansController")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","Sans", new { id = item.MaSan },"SansController")),*/
grid.Column("Chức năng", format: item => new System.Web.WebPages.HelperResult(__razor_template_writer => {


#line default
#line hidden

#line 15 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh                \Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                        __o = Url.Action("Edit",
                        new { id = item.MaDS} );


#line default
#line hidden

#line 16 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh                \Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                        __o = Url.Action("Details",
                        new { id = item.MaDS} );


#line default
#line hidden

#line 17 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh                \Admin\Views\DatSans\BaoCaoThongKe.cshtml"
                        __o = Url.Action("Delete",
                        new { id = item.MaDS});


#line default
#line hidden

#line 18 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
     })),

}
);


#line default
#line hidden

#line 19 "C:\Users\pnt22\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\4\QuanLySanBanh                                                                                                                                        __o = ViewBag.TB;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_BaoCaoThongKe_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_BaoCaoThongKe_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\anhla\AppData\Local\Temp\2802F358BD9B3170500B5AD14CEF9858B571\2\QuanLySanBanh\QuanLySanBanh\Areas\Admin\Views\DatSans\BaoCaoThongKe.cshtml"
  
    ViewBag.Title = "BaoCaoThongKe";
    Layout = "~/Views/Shared/_Layout2.cshtml";


#line default
#line hidden
}
}
}
